### PR TITLE
Add some nice styling

### PR DESCRIPTION
**Pull request by endorfin**
feel free to merge ;)

### CODE REVIEW

**Comment by phallstrom** [comment]
@endorfin Nice!  

Would you be open to doing some modifications?
- I don't always symlink my Pow apps.  Can you check to make sure it's a symlink before calling readlink (and then handle both cases)?
- Can you add some styling to indicate when the resulting path doesn't exist (ie. I've removed the directory, but not the symlink in .pow)?
- Can you adjust the layout so that when viewed on mobile that POW image is hidden and things are tightened up so we don't have to scroll as much?  Perhaps drop the file path line?
- You're listing of the file path is interesting.  Can you tweak it to make it it's own link (just put 'fixme' for the href for now)?  I'll add some code to make it open that folder in the Finder.

**Comment by endorfin** [comment]
Point 1 and 2 is done. Styling optimization comes tomorrow ;)

**Comment by endorfin** [comment]
bildschirmfoto 2013-09-17 um 00 31 28

**Comment by phallstrom** [comment]
@endorfin Not sure how I missed your follow up styling.  Sorry about that.  I've merged it all in and added your name to the README (let me know if you'd like something different there).

Nice work!

**Comment by endorfin** [comment]
Great, thanks!

**Pull request merged**
